name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_django_job:
    uses: Sai-Santhan/django-kubernetes/.github/workflows/test-django.yaml@master
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: django-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Login to DO Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Build Container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/my-private-registry333/django-k8s-web:latest \
            -t registry.digitalocean.com/my-private-registry333/django-k8s-web:${GITHUB_SHA::7} \
            .
      - name: Push Image to DO Container Registry
        run: |
          docker push registry.digitalocean.com/my-private-registry333/django-k8s-web --all-tags
      - name: K8s cluster kubeconfig file with short-lived credentials
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update Deployment image
        run: |
          kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/my-private-registry333/django-k8s-web:${GITHUB_SHA::7}
      - name: Wait for Rollout to finish
        run: |
          kubectl rollout status deployment/django-k8s-web-deployment
      - name: Migrate Database Command
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
