name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_django_job:
    uses: Sai-Santhan/django-kubernetes/.github/workflows/test-django.yaml@master
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Login to DO Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Build Container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/my-private-registry333/django-k8s-web:latest \
            -t registry.digitalocean.com/my-private-registry333/django-k8s-web:${GITHUB_SHA::7} \
            .
      - name: Push Image to DO Container Registry
        run: |
          docker push registry.digitalocean.com/my-private-registry333/django-k8s-web --all-tags
