name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django:
    uses: Sai-Santhan/django-kubernetes/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
